spring:
    datasource:
        postgresql:
            url: jdbc:postgresql://172.16.20.102:5433/logging
            username: logger_user
            password: logger_user
        hikari:
            maximum-pool-size: 10
            connection-timeout: 5000